# Generated by Django 5.1 on 2024-10-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='Product',
            new_name='product',
        ),
    ]
