# Generated by Django 5.1 on 2024-11-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productview_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='viewed_at',
        ),
    ]
