# Generated by Django 5.1 on 2024-11-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_productview_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_fa_name',
            field=models.CharField(default='نام محصول', max_length=100),
        ),
    ]
